export const BATTLE_CONFIG = {
  armorDamageConstant: 3,
  minDamageMultiplier: 0.05,
  power: {
    averageEnemyArmor: 20,
    averageExtraTargets: 1.5,
    averageIncomingAttackSpeed: 1,
    referenceAttackWeight: 0.65,
    referenceHealthWeight: 0.3,
    referenceArmorWeight: 0.05,
    referenceTargetTtk: 8,
    expectedArmorToAttackRatio: 0.6,
    critEfficiency: 0.65,
    attackSpeedEfficiency: 0.85,
    hitImpactEfficiency: 0.45,
    minHitImpactMultiplier: 0.85,
    maxHitImpactMultiplier: 1.6,
    areaEfficiency: 0.55,
    lifestealEfficiency: 0.35,
    thornsEfficiency: 1.3,
    defensePowerWeight: 0.45,
    offensePowerWeight: 0.55,
  },
}
