export const BATTLE_CONFIG = {
  armorDamageConstant: 3,
  minDamageMultiplier: 0.05,
  power: {
    averageExtraTargets: 1.5,
    opponentScaleAttackWeight: 0.45,
    opponentScaleHealthWeight: 0.35,
    opponentScaleArmorWeight: 0.2,
    critEfficiency: 0.65,
    attackSpeedEfficiency: 0.85,
    hitImpactEfficiency: 0.45,
    minHitImpactMultiplier: 0.85,
    maxHitImpactMultiplier: 1.6,
    areaEfficiency: 1,
    lifestealEfficiency: 0.35,
    thornsEfficiency: 1.3,
    defensePowerWeight: 0.45,
    offensePowerWeight: 0.55,
  },
}
